services:
  recommender:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recommender
    expose:
      - 65535:65535
    volumes:
      - ../resume:/resume:ro
    networks:
      - careerspeak

networks:
  careerspeak:
    external: true
